Crm/Crm/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from app01 import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('reg/',views.reg),

    path('register/', views.RegisterView.as_view()),

    path('login/',views.login),
    path('index/',views.index),
    path('get_valid_img/',views.get_valid_img),
    path('customers/list/', views.CustomerView.as_view(), name="customers_list"),
    path('customers/self/', views.CustomerView.as_view(),name = "customers_self"),
    path("customers/all/",views.CustomerView.as_view()),
    path('logout/', views.logout),
    path('customers/add/',views.AddCustomerView.as_view(),name="addcustomers"),
    re_path('customer/edit/(\d+)', views.EditCustomerView.as_view(),name="editcustomers"),
    re_path('customer/del/(\d+)', views.EditCustomerView.as_view(),name="delcustomers"),
    path('customer/recoder/self/',views.RecoderCustomerView.as_view(),name='recodercustomer'),
    path('customer/recoder/public/',views.RecoderCustomerView.as_view(),name='recoderpublic'),
    path('customer/recoder/',views.RecoderCustomerView.as_view(),name='recoder'),
    path('recoder/add/',views.AddrecoderCustomer.as_view(),name="addrecoder"),
    re_path('recoder/edit/(\d+)',views.EditrecodrView.as_view(),name="editrecoder"),
    re_path('recoder/del/(\d+)',views.EditrecodrView.as_view(),name="delrecoder"),
    path('Enrollment/list/',views.EnrollmentView.as_view(),name='enroll'),
    re_path('Enrollment/edit/(\d+)',views.EditAddenrollment.as_view(),name='enrolledit'),
    re_path('Enrollment/add/',views.EditAddenrollment.as_view(),name='enrolladd'),

    # 班级学习记录  #批量创建走的这个路径
    path("ClassStudyRecord/list/",views.ClassStudyRecordView.as_view(),name = "classsturecoder"),
    re_path("ClassStudyRecord/edit/(\d+)",views.ClassStudyRecordAdd_Edit.as_view(),name = "classstuedit"),
    path("ClassStudyRecord/add/",views.ClassStudyRecordAdd_Edit.as_view(),name = "classstuadd"),
    re_path("ClassStudyRecord/del/(\d+)",views.ClassStudyRecordAdd_Edit.as_view(),name = "classstudel"),

    # 学生学习记录
    path("StudentStudyRecord/list/", views.StudentStudyRecordView.as_view(), name="studentsturecoder"),
    re_path("StudentStudyRecord/edit/(\d+)", views.StudentStudyRecordAdd_Edit.as_view(), name="studentstuedit"),
    path("StudentStudyRecord/add/", views.StudentStudyRecordAdd_Edit.as_view(), name="studenttuadd"),
    re_path("StudentStudyRecord/del/(\d+)", views.StudentStudyRecordAdd_Edit.as_view(), name="studentstudel"),

    # 录入分数
    re_path('ScoreRecord/show/(\d+)/', views.RecordScoreView.as_view(), name="record_score"),
    path('customer/tongji/', views.TongJiView.as_view(), name="tongji"),
    re_path(r'', include('rbac.urls', )),
]

Crm/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from app01 import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('reg/',views.reg),

    path('register/', views.RegisterView.as_view()),

    path('login/',views.login),
    path('index/',views.index),
    path('get_valid_img/',views.get_valid_img),
    path('customers/list/', views.CustomerView.as_view(), name="customers_list"),
    path('customers/self/', views.CustomerView.as_view(),name = "customers_self"),
    path("customers/all/",views.CustomerView.as_view()),
    path('logout/', views.logout),
    path('customers/add/',views.AddCustomerView.as_view(),name="addcustomers"),
    re_path('customer/edit/(\d+)', views.EditCustomerView.as_view(),name="editcustomers"),
    re_path('customer/del/(\d+)', views.EditCustomerView.as_view(),name="delcustomers"),
    path('customer/recoder/self/',views.RecoderCustomerView.as_view(),name='recodercustomer'),
    path('customer/recoder/public/',views.RecoderCustomerView.as_view(),name='recoderpublic'),
    path('customer/recoder/',views.RecoderCustomerView.as_view(),name='recoder'),
    path('recoder/add/',views.AddrecoderCustomer.as_view(),name="addrecoder"),
    re_path('recoder/edit/(\d+)',views.EditrecodrView.as_view(),name="editrecoder"),
    re_path('recoder/del/(\d+)',views.EditrecodrView.as_view(),name="delrecoder"),
    path('Enrollment/list/',views.EnrollmentView.as_view(),name='enroll'),
    re_path('Enrollment/edit/(\d+)',views.EditAddenrollment.as_view(),name='enrolledit'),
    re_path('Enrollment/add/',views.EditAddenrollment.as_view(),name='enrolladd'),

    # 班级学习记录  #批量创建走的这个路径
    path("ClassStudyRecord/list/",views.ClassStudyRecordView.as_view(),name = "classsturecoder"),
    re_path("ClassStudyRecord/edit/(\d+)",views.ClassStudyRecordAdd_Edit.as_view(),name = "classstuedit"),
    path("ClassStudyRecord/add/",views.ClassStudyRecordAdd_Edit.as_view(),name = "classstuadd"),
    re_path("ClassStudyRecord/del/(\d+)",views.ClassStudyRecordAdd_Edit.as_view(),name = "classstudel"),

    # 学生学习记录
    path("StudentStudyRecord/list/", views.StudentStudyRecordView.as_view(), name="studentsturecoder"),
    re_path("StudentStudyRecord/edit/(\d+)", views.StudentStudyRecordAdd_Edit.as_view(), name="studentstuedit"),
    path("StudentStudyRecord/add/", views.StudentStudyRecordAdd_Edit.as_view(), name="studenttuadd"),
    re_path("StudentStudyRecord/del/(\d+)", views.StudentStudyRecordAdd_Edit.as_view(), name="studentstudel"),

    # 录入分数
    re_path('ScoreRecord/show/(\d+)/', views.RecordScoreView.as_view(), name="record_score"),
    path('customer/tongji/', views.TongJiView.as_view(), name="tongji"),
    re_path(r'', include('rbac.urls', )),
]

Crm/app01/forms/Userform.py
from django import forms
from app01.models import *

from django.forms import widgets as wid
from django.core.exceptions import NON_FIELD_ERRORS, ValidationError
import re
class UserModelForm(forms.ModelForm):
    r_pwd = forms.CharField(error_messages={'r_pwd':"不能为空"}, label='确认密码',
                            widget=wid.PasswordInput(attrs={"class": "form-control"}))
    # r_pwd = forms.CharField(label='确认密码',error_messages={'r_pwd':"不能为空"})
    # widgets={'r_pwd':wid.PasswordInput(attrs={'type':"password"})}
    class Meta:
        model=UserInfo
        fields=['username','email','gender','tel',"password"]
        # fields = "__all__"
        labels={'username':"用户名",'password':'密码','email':'邮箱',"tel":"电话",'gender':"性别"}
        help_texts={'username':'请输入用户名',"password":'请输入密码',"email":'请输入163邮箱','tel':'请输入电话号码'}
        widgets={'password':wid.PasswordInput(attrs={'placeholder':'请输入由数字与字母组成的长度不小于5密码'}),'username':wid.TextInput(attrs={'placeholder':'请输入不少于五位的用户名'}),'email':wid.EmailInput(attrs={'placeholder':'请输入163邮箱'}),'tel':wid.TextInput(attrs={'placeholder':'请输入手机号'})}

        #如果有时间限制格式:
            # widgets={'pub_date':wid.TextInput(attrs={'type':'date'})}


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for filed in self.fields.values():
            print(filed.error_messages)
            filed.error_messages={"required":"不能为空","invalid": "格式错误"}
            filed.widget.attrs.update({'class': 'form-control'})
    #
    def clean_tel(self):
        tel=self.cleaned_data.get('tel')
        if tel:
            if re.match(r'^(13\d|14[5|7]|15\d|166|17[3|6|7]|18\d)\d{8}$',tel):
                return tel
        else:
            raise ValidationError("手机号码非法")
    def clean_email(self):
        import re
        email = self.cleaned_data.get('email')
        if re.search('[0-9a-zA-Z]+@163\.com', email):
            return email
        else:
            if email=='':
                raise  ValidationError('邮箱不能为空')
            else:
                raise ValidationError('请输入163.com邮箱')
    def clean_username(self):
        username=self.cleaned_data.get('username')
        ret = UserInfo.objects.filter(username=username)
        if ret:
            raise ValidationError('用户名已存在')
        else:
            return username

    def clean(self):
        password =  self.cleaned_data.get('password')
        r_pwd= self.cleaned_data.get('r_pwd')
        print(password,r_pwd)

        if password==r_pwd:
            print('haha')
            return self.cleaned_data
        else:
            self.add_error('r_pwd',ValidationError('密码不一致'))

    def save(self, commit=True):
        # Save the provided password in hashed format
        # 继承基类的save()
        user = super(UserModelForm, self).save(commit=False)
        # 把明文密码改成密文
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

Crm/app01/forms/classstudyrecorder.py
from django import forms
from app01.models import ClassStudyRecord
class ClassStudyRecordForm(forms.ModelForm):
    class Meta:
        model = ClassStudyRecord
        fields="__all__"
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in self.fields.values():
            from multiselectfield.forms.fields import MultiSelectFormField
            from django.forms.fields import BooleanField
            if isinstance(field,BooleanField):
                continue
            if not isinstance(field, MultiSelectFormField):
                field.widget.attrs.update({'class': 'form-control'})

Crm/app01/forms/customers.py
from django import forms
from app01.models import Customer
class CustomerModelForm(forms.ModelForm):
    class Meta:
        model=Customer
        fields="__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            from multiselectfield.forms.fields import MultiSelectFormField
            if not isinstance(field,MultiSelectFormField):
                field.widget.attrs.update({'class':'form-control'})

Crm/app01/forms/eroll.py
from django import forms
from app01.models import Enrollment
class ErollmentForm(forms.ModelForm):
    class Meta:
        model=Enrollment
        exclude=['delete_status']
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in  self.fields.values():
            from multiselectfield.forms.fields import MultiSelectFormField
            if not isinstance(field, MultiSelectFormField):
                field.widget.attrs.update({'class': 'form-control'})

Crm/app01/forms/recoder.py
from django import forms
from app01.models import ConsultRecord
class RecoderCustomerFrom(forms.ModelForm):
    class Meta:
        model = ConsultRecord
        fields = '__all__'

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in self.fields.values():
            from multiselectfield.forms.fields import MultiSelectFormField
            if not isinstance(field,MultiSelectFormField):
                field.widget.attrs.update({'class':'form-control'})

Crm/app01/forms/studentstudy.py
from django import forms
from app01.models import StudentStudyRecord
class StudentStudyRecordForm(forms.ModelForm):
    class Meta:
        model = StudentStudyRecord
        fields="__all__"
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in self.fields.values():
            from multiselectfield.forms.fields import MultiSelectFormField
            from django.forms.fields import BooleanField
            if isinstance(field,BooleanField):
                continue
            if not isinstance(field, MultiSelectFormField):
                field.widget.attrs.update({'class': 'form-control'})

app01/forms/Userform.py
from django import forms
from app01.models import *

from django.forms import widgets as wid
from django.core.exceptions import NON_FIELD_ERRORS, ValidationError
import re
class UserModelForm(forms.ModelForm):
    r_pwd = forms.CharField(error_messages={'r_pwd':"不能为空"}, label='确认密码',
                            widget=wid.PasswordInput(attrs={"class": "form-control"}))
    # r_pwd = forms.CharField(label='确认密码',error_messages={'r_pwd':"不能为空"})
    # widgets={'r_pwd':wid.PasswordInput(attrs={'type':"password"})}
    class Meta:
        model=UserInfo
        fields=['username','email','gender','tel',"password"]
        # fields = "__all__"
        labels={'username':"用户名",'password':'密码','email':'邮箱',"tel":"电话",'gender':"性别"}
        help_texts={'username':'请输入用户名',"password":'请输入密码',"email":'请输入163邮箱','tel':'请输入电话号码'}
        widgets={'password':wid.PasswordInput(attrs={'placeholder':'请输入由数字与字母组成的长度不小于5密码'}),'username':wid.TextInput(attrs={'placeholder':'请输入不少于五位的用户名'}),'email':wid.EmailInput(attrs={'placeholder':'请输入163邮箱'}),'tel':wid.TextInput(attrs={'placeholder':'请输入手机号'})}

        #如果有时间限制格式:
            # widgets={'pub_date':wid.TextInput(attrs={'type':'date'})}


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for filed in self.fields.values():
            print(filed.error_messages)
            filed.error_messages={"required":"不能为空","invalid": "格式错误"}
            filed.widget.attrs.update({'class': 'form-control'})
    #
    def clean_tel(self):
        tel=self.cleaned_data.get('tel')
        if tel:
            if re.match(r'^(13\d|14[5|7]|15\d|166|17[3|6|7]|18\d)\d{8}$',tel):
                return tel
        else:
            raise ValidationError("手机号码非法")
    def clean_email(self):
        import re
        email = self.cleaned_data.get('email')
        if re.search('[0-9a-zA-Z]+@163\.com', email):
            return email
        else:
            if email=='':
                raise  ValidationError('邮箱不能为空')
            else:
                raise ValidationError('请输入163.com邮箱')
    def clean_username(self):
        username=self.cleaned_data.get('username')
        ret = UserInfo.objects.filter(username=username)
        if ret:
            raise ValidationError('用户名已存在')
        else:
            return username

    def clean(self):
        password =  self.cleaned_data.get('password')
        r_pwd= self.cleaned_data.get('r_pwd')
        print(password,r_pwd)

        if password==r_pwd:
            print('haha')
            return self.cleaned_data
        else:
            self.add_error('r_pwd',ValidationError('密码不一致'))

    def save(self, commit=True):
        # Save the provided password in hashed format
        # 继承基类的save()
        user = super(UserModelForm, self).save(commit=False)
        # 把明文密码改成密文
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

app01/forms/classstudyrecorder.py
from django import forms
from app01.models import ClassStudyRecord
class ClassStudyRecordForm(forms.ModelForm):
    class Meta:
        model = ClassStudyRecord
        fields="__all__"
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in self.fields.values():
            from multiselectfield.forms.fields import MultiSelectFormField
            from django.forms.fields import BooleanField
            if isinstance(field,BooleanField):
                continue
            if not isinstance(field, MultiSelectFormField):
                field.widget.attrs.update({'class': 'form-control'})

app01/forms/customers.py
from django import forms
from app01.models import Customer
class CustomerModelForm(forms.ModelForm):
    class Meta:
        model=Customer
        fields="__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            from multiselectfield.forms.fields import MultiSelectFormField
            if not isinstance(field,MultiSelectFormField):
                field.widget.attrs.update({'class':'form-control'})

app01/forms/eroll.py
from django import forms
from app01.models import Enrollment
class ErollmentForm(forms.ModelForm):
    class Meta:
        model=Enrollment
        exclude=['delete_status']
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in  self.fields.values():
            from multiselectfield.forms.fields import MultiSelectFormField
            if not isinstance(field, MultiSelectFormField):
                field.widget.attrs.update({'class': 'form-control'})

app01/forms/recoder.py
from django import forms
from app01.models import ConsultRecord
class RecoderCustomerFrom(forms.ModelForm):
    class Meta:
        model = ConsultRecord
        fields = '__all__'

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in self.fields.values():
            from multiselectfield.forms.fields import MultiSelectFormField
            if not isinstance(field,MultiSelectFormField):
                field.widget.attrs.update({'class':'form-control'})

app01/forms/studentstudy.py
from django import forms
from app01.models import StudentStudyRecord
class StudentStudyRecordForm(forms.ModelForm):
    class Meta:
        model = StudentStudyRecord
        fields="__all__"
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in self.fields.values():
            from multiselectfield.forms.fields import MultiSelectFormField
            from django.forms.fields import BooleanField
            if isinstance(field,BooleanField):
                continue
            if not isinstance(field, MultiSelectFormField):
                field.widget.attrs.update({'class': 'form-control'})

app01/templates/editaddenrollment.html
{% extends 'base.html' %}
{% block content %}
    <div class="content-wrapper">
         {% load my %}
         {% bread request %}
          <!-- Content Header (Page header) -->
          <section class="content-header">
              <h1>
                  {% if obj %}
                    编辑
                {% else %}
                    添加
                {% endif %}
                  <small>Optional description</small>
              </h1>
              <ol class="breadcrumb">
                  <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
                  <li class="active">Here</li>
              </ol>
          </section>




          <!-- Main content -->
          <section class="content">

            <div class="row">
                  <div class="col-md-8 col-md-offset-2">
                      <form action="" method="post">
                      {% csrf_token %}
                         {% for field in form %}
                             <label for="">{{ field.label }}</label>
                             {{ field }} <span>{{ form.errors.0 }}</span>
                         {% endfor %}
                            <button class="btn btn-default pull-right">提交</button>
                      </form>
                  </div>
            </div>

          </section>
          <!-- /.content -->
      </div>
{% endblock %}

app01/templates/enrollment.html
{% extends 'base.html' %}
{% block content %}
  <div class="content-wrapper">
         {% load my %}
         {% bread request %}
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h3 class="change">
               报名表
            </h3>

            <!--模糊查询的form 表单      完成-->
            <form action=""  method="get" class="pull-right">
                 <ol class="breadcrumb">
                     <li>

{#                         select里必须随便写个name给作为键去组成#}
                       <select name="field" id="s1" class="form-control" style="display: inline-block;width: 110px">
                            <option value="name">姓名</option>
                            <option value="sex">性别</option>
                            <option value="qq">QQ</option>
                            <option value="phone">手机号</option>
                            <option value="source">客户来源</option>
                            <option value="date">查询日期</option>
                            <option value="status">状态</option>
                            <option value="consultant">销售</option>
                            <option value="class_list">已报班级</option>
                      </select>

                <input style="height: 32px;width: 100px" placeholder="请输入关键字" type="text" name="q">
                <input id="searchbtn" type= 'submit' style="height: 32px;width: 60px;vertical-align: 0px" class="btn btn-success " value="搜索">
                 </li>
                </ol>
            </form>
        </section>

        <!-- Main content -->
           <form action="" method="post">
           {% csrf_token %}
              <ol class="breadcrumb">
                     <select name="action" id="" class="form-control" style="display: inline-block;width: 240px">
                         <option value="">请选择批量处理方法</option>
                         <option value="patch_delete">删除</option>
                     </select>
                    <button style="vertical-align: 0px" class="btn btn-danger">提交</button>
            </ol>
            <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                        <div class="box-header">
                            <a style="font-size: 14px" href="{% url "enrolladd" %}{{ next }}" class="box-title btn btn-success btn-sm">添加客户</a>
                            <a style="font-size: 14px" class="box-title btn btn-warning btn-sm" id="allbtn">全选</a>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            <table  id="example2" class="text-center table table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th>选择</th>
                                        <th>编号</th>
                                        <th>客户名称</th>
                                        <th>报名原因</th>
                                        <th>学完想达到的具体期望</th>
                                        <th>报名日期</th>
                                        <th>备注</th>
                                        <th>所报班级</th>
                                        <th>编辑</th>
                                        <th>删除</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for eroll in eroll_list %}
                                <tr>
                                    <td><input type="checkbox" name="select_id" value="{{ eroll.pk }}"></td>
                                    <td>{{ forloop.counter|add:pagination.num}}</td>
                                    <td>{{ eroll.customer.name }}</td>
                                    <td>{{ eroll.why_us}}</td>
                                    <td>{{ eroll.your_expectation }}</td>
                                    <td>{{ eroll.enrolled_date|date:"Y-m-d" }}</td>
                                    <td>{{ eroll.memo }}</td>
                                    <td>{{ eroll.enrolment_class }}</td>
{#                                    以前是这样的#}
{#                                    <td>{% for customers in customers.class_list.all %}#}
{#                                        <span>{{ customers }}</span>#}
{#                                        {% if  not forloop.last %}#}
{#                                            ,#}
{#                                        {% endif %}#}
{#                                    {% endfor %}#}
{#                                    </td>#}
{#                                新学了一种#}

                                    <td><a href="{% url 'enrolledit' eroll.pk %}" class="btn btn-success btn-sm"> <i class="fa fa-edit  fa-lg"></i> </a>
                                    </td>
                                    <td><a href="" class="btn btn-success btn-sm"><i class="fa fa-trash-o fa-lg"></i> </a></td>

                                </tr>
                                {% endfor %}



                                </tbody>
                            </table>
                            <nav aria-label="Page navigation" class="pull-right">
                                  <ul class="pagination">
                                        {{ pagination.page_html|safe }}
                                  </ul>
                            </nav>
                        </div>
                        <!-- /.box-body -->
                    </div>
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
           </form>

        <!-- /.content -->
    </div>
{% endblock %}

app01/templates/index.html
{% extends 'base.html' %}

app01/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/bootstrap-3.3.7/dist/css/bootstrap.css">

    <link rel="stylesheet" href="/static/node_modules/selfwrite.css">
     <script src="/static/node_modules/jquery/dist/jquery.js"></script>
    <script src="/static/bootstrap-3.3.7/dist/js/bootstrap.js"></script>
</head>
<body>
     <div class="modal-body">

            {% csrf_token %}
            <div class="container">
                <div class="row">
                    <div class="col-md-6 col-md-offset-2">
                        <form >
                            {% csrf_token %}
                            <div class="form-group">
                                <lable id="user" >用户名</lable>
            {#                    一定要设name#}
                                <input type="text" placeholder="请输入用户名"  class="form-control" name="user" id="user">
                            </div>
                            <div class="form-group">
                                <lable id="pwd" >密码</lable>
            {#                    一定要设name#}
                                <input type="password" placeholder="请输入密码" class="form-control" name="pwd" id="pwd">
                            </div>
                             <div class="form-group">
                                <lable id="validcode" >验证码</lable>

                                 <div class= 'row'>
                                    <div class="col-md-6">
                                        <input type="text" placeholder="请输入验证码" class="form-control" name="validcode" id="validcode">
                                    </div>
                                     <div class="col-md-4">
                                            <img id="valid_code_img" src="/get_valid_img/" pk='yanzhengma' width="180px" height="35px" alt="">
                                     </div>
                                     <div class="col-md-2">
                                         <a href="javascript:void(0)" class="btn btn-success changebtn">换一张</a>
                                     </div>
                                 </div>

{#                                一定要设name#}
                            </div>
                            <p><span style="color: red" id="error"></span></p>
                                <input type="button" value="提交" class="btn btn-danger loginbtn">
                                <a href="/reg/" type="button" class="btn btn-danger">还没有注册点我,注册</a>
                                <a href="/index/" type="button" class="btn btn-danger ">返回首页</a>
                        </form>
                    </div>
                </div>
            </div>
     </div>
</body>
<script>
    $(".loginbtn").click(function () {
        alert(111)

        $.ajax({
            url:'/login/',
            type:'post',
            data:{
                user:$('[name=user]').val(),
                pwd:$('[name=pwd]').val(),
                validcode:$('[name=validcode]').val(),
                csrfmiddlewaretoken:$("[name='csrfmiddlewaretoken']").val()
            },
            success:function (resonse) {
                ret=JSON.parse(resonse);
                console.log(ret)
                if (ret.error){
                   $("#error").html(ret.error)
                }
                else{
                    location.href='/index/'
                }
            }
        })
    })
    $('.changebtn').click(function () {
         $('[pk=yanzhengma]')[0].src+='?'
    })
</script>
</html>

app01/templates/reg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/bootstrap-3.3.7/dist/css/bootstrap.css">
    <script src="/static/node_modules/jquery/dist/jquery.js"></script>
    <style>
        .error{
            color: red;
        }
    </style>
</head>
<body>
    <h3>欢迎注册</h3>
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-2">
                <form novalidate>
                {% csrf_token %}
                  {% for field in form %}
                        <div class="form-group">
                             <label for="title">{{ field.label }}</label>
                             {{ field }}
                             <span class="error"></span>
{#                             {% if field.label == '密码' %}#}
{#                                <div class="form-group">#}
{#                                     <label for="title" style="margin-top:10px ">确认密码</label>#}
{#                                     <input type="password"   class="form-control" name="r_pwd" id="id_r_pwd">#}
{#                                     <span class="error"></span>#}
{#                                 </div>#}
{#                             {% endif %}#}

                        </div>
                 {% endfor %}
    </form>
    <input type="button" id="regbtn" value="提交" class="btn btn-success  pull-right">
            </div>
        </div>
    </div>
    <script>

{#        写函数#}
        $('#regbtn').click(function () {
           $.ajax({
               url:'/reg/',
               type:'post',
               data:{
                   username:$('[name=username]').val(),
                   password:$('[name=password]').val(),
                   r_pwd:$('[name=r_pwd]').val(),
                   email:$('[name=email]').val(),
                   gender:$('[name=gender]').val(),
                   tel:$('[name=tel]').val(),
                   csrfmiddlewaretoken:$("[name='csrfmiddlewaretoken']").val()
               },
               success:function (response) {
                   if (response.user) {
                       console.log(response)
                    location.href='/login/'
                   } else {
                       console.log(response);
                       $("span").html("")
                       $.each(response.errors, function (i, j) {
                           $('#id_' + i).next('span').html(j)
                       })
                   }
               }
           })
        })
    </script>

</body>


</html>

app01/templates/static_index.html
{% extends 'base.html' %}