Crm/Crm/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from app01 import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('reg/',views.reg),

    path('register/', views.RegisterView.as_view()),

    path('login/',views.login),
    path('index/',views.index),
    path('get_valid_img/',views.get_valid_img),
    path('customers/list/', views.CustomerView.as_view(), name="customers_list"),
    path('customers/self/', views.CustomerView.as_view(),name = "customers_self"),
    path("customers/all/",views.CustomerView.as_view()),
    path('logout/', views.logout),
    path('customers/add/',views.AddCustomerView.as_view(),name="addcustomers"),
    re_path('customer/edit/(\d+)', views.EditCustomerView.as_view(),name="editcustomers"),
    re_path('customer/del/(\d+)', views.EditCustomerView.as_view(),name="delcustomers"),
    path('customer/recoder/self/',views.RecoderCustomerView.as_view(),name='recodercustomer'),
    path('customer/recoder/public/',views.RecoderCustomerView.as_view(),name='recoderpublic'),
    path('customer/recoder/',views.RecoderCustomerView.as_view(),name='recoder'),
    path('recoder/add/',views.AddrecoderCustomer.as_view(),name="addrecoder"),
    re_path('recoder/edit/(\d+)',views.EditrecodrView.as_view(),name="editrecoder"),
    re_path('recoder/del/(\d+)',views.EditrecodrView.as_view(),name="delrecoder"),
    path('Enrollment/list/',views.EnrollmentView.as_view(),name='enroll'),
    re_path('Enrollment/edit/(\d+)',views.EditAddenrollment.as_view(),name='enrolledit'),
    re_path('Enrollment/add/',views.EditAddenrollment.as_view(),name='enrolladd'),

    # 班级学习记录  #批量创建走的这个路径
    path("ClassStudyRecord/list/",views.ClassStudyRecordView.as_view(),name = "classsturecoder"),
    re_path("ClassStudyRecord/edit/(\d+)",views.ClassStudyRecordAdd_Edit.as_view(),name = "classstuedit"),
    path("ClassStudyRecord/add/",views.ClassStudyRecordAdd_Edit.as_view(),name = "classstuadd"),
    re_path("ClassStudyRecord/del/(\d+)",views.ClassStudyRecordAdd_Edit.as_view(),name = "classstudel"),

    # 学生学习记录
    path("StudentStudyRecord/list/", views.StudentStudyRecordView.as_view(), name="studentsturecoder"),
    re_path("StudentStudyRecord/edit/(\d+)", views.StudentStudyRecordAdd_Edit.as_view(), name="studentstuedit"),
    path("StudentStudyRecord/add/", views.StudentStudyRecordAdd_Edit.as_view(), name="studenttuadd"),
    re_path("StudentStudyRecord/del/(\d+)", views.StudentStudyRecordAdd_Edit.as_view(), name="studentstudel"),

    # 录入分数
    re_path('ScoreRecord/show/(\d+)/', views.RecordScoreView.as_view(), name="record_score"),
    path('customer/tongji/', views.TongJiView.as_view(), name="tongji"),
    re_path(r'', include('rbac.urls', )),
]

Crm/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from app01 import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('reg/',views.reg),

    path('register/', views.RegisterView.as_view()),

    path('login/',views.login),
    path('index/',views.index),
    path('get_valid_img/',views.get_valid_img),
    path('customers/list/', views.CustomerView.as_view(), name="customers_list"),
    path('customers/self/', views.CustomerView.as_view(),name = "customers_self"),
    path("customers/all/",views.CustomerView.as_view()),
    path('logout/', views.logout),
    path('customers/add/',views.AddCustomerView.as_view(),name="addcustomers"),
    re_path('customer/edit/(\d+)', views.EditCustomerView.as_view(),name="editcustomers"),
    re_path('customer/del/(\d+)', views.EditCustomerView.as_view(),name="delcustomers"),
    path('customer/recoder/self/',views.RecoderCustomerView.as_view(),name='recodercustomer'),
    path('customer/recoder/public/',views.RecoderCustomerView.as_view(),name='recoderpublic'),
    path('customer/recoder/',views.RecoderCustomerView.as_view(),name='recoder'),
    path('recoder/add/',views.AddrecoderCustomer.as_view(),name="addrecoder"),
    re_path('recoder/edit/(\d+)',views.EditrecodrView.as_view(),name="editrecoder"),
    re_path('recoder/del/(\d+)',views.EditrecodrView.as_view(),name="delrecoder"),
    path('Enrollment/list/',views.EnrollmentView.as_view(),name='enroll'),
    re_path('Enrollment/edit/(\d+)',views.EditAddenrollment.as_view(),name='enrolledit'),
    re_path('Enrollment/add/',views.EditAddenrollment.as_view(),name='enrolladd'),

    # 班级学习记录  #批量创建走的这个路径
    path("ClassStudyRecord/list/",views.ClassStudyRecordView.as_view(),name = "classsturecoder"),
    re_path("ClassStudyRecord/edit/(\d+)",views.ClassStudyRecordAdd_Edit.as_view(),name = "classstuedit"),
    path("ClassStudyRecord/add/",views.ClassStudyRecordAdd_Edit.as_view(),name = "classstuadd"),
    re_path("ClassStudyRecord/del/(\d+)",views.ClassStudyRecordAdd_Edit.as_view(),name = "classstudel"),

    # 学生学习记录
    path("StudentStudyRecord/list/", views.StudentStudyRecordView.as_view(), name="studentsturecoder"),
    re_path("StudentStudyRecord/edit/(\d+)", views.StudentStudyRecordAdd_Edit.as_view(), name="studentstuedit"),
    path("StudentStudyRecord/add/", views.StudentStudyRecordAdd_Edit.as_view(), name="studenttuadd"),
    re_path("StudentStudyRecord/del/(\d+)", views.StudentStudyRecordAdd_Edit.as_view(), name="studentstudel"),

    # 录入分数
    re_path('ScoreRecord/show/(\d+)/', views.RecordScoreView.as_view(), name="record_score"),
    path('customer/tongji/', views.TongJiView.as_view(), name="tongji"),
    re_path(r'', include('rbac.urls', )),
]

Crm/app01/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import AbstractUser



from django.db import models
from django.contrib import auth
from django.core.exceptions import PermissionDenied
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager, User
from django.utils.translation import ugettext_lazy as _
from multiselectfield import MultiSelectField
from django.utils.safestring import mark_safe

course_choices = (('LinuxL', 'Linux中高级'),
                  ('PythonFullStack', 'Python高级全栈开发'),)

class_type_choices = (('fulltime', '脱产班',),
                      ('online', '网络班'),
                      ('weekend', '周末班',),)

source_type = (('qq', "qq群"),
               ('referral', "内部转介绍"),
               ('website', "官方网站"),
               ('baidu_ads', "百度推广"),
               ('office_direct', "直接上门"),
               ('WoM', "口碑"),
               ('public_class', "公开课"),
               ('website_luffy', "路飞官网"),
               ('others', "其它"),)

enroll_status_choices = (('signed', "已报名"),
                         ('unregistered', "未报名"),
                         ('studying', '学习中'),
                         ('paid_in_full', "学费已交齐"))

seek_status_choices = (('A', '近期无报名计划'), ('B', '1个月内报名'), ('C', '2周内报名'), ('D', '1周内报名'),
                       ('E', '定金'), ('F', '到班'), ('G', '全款'), ('H', '无效'),)
pay_type_choices = (('deposit', "订金/报名费"),
                    ('tuition', "学费"),
                    ('transfer', "转班"),
                    ('dropout', "退学"),
                    ('refund', "退款"),)

attendance_choices = (('checked', "已签到"),
                      ('vacate', "请假"),
                      ('late', "迟到"),
                      ('absence', "缺勤"),
                      ('leave_early', "早退"),)

score_choices = ((100, 'A+'),
                 (90, 'A'),
                 (85, 'B+'),
                 (80, 'B'),
                 (70, 'B-'),
                 (60, 'C+'),
                 (50, 'C'),
                 (40, 'C-'),
                 (0, ' D'),
                 (-1, 'N/A'),
                 (-100, 'COPY'),
                 (-1000, 'FAIL'),)

from rbac.models import User1
class UserInfo(AbstractUser):
    tel=models.CharField(max_length=32,null=True,blank=True)
    gender=models.IntegerField(choices=((1,"男"),(2,"女")),default=1)
    user = models.OneToOneField(to=User1,null=True,blank= True,on_delete=models.CASCADE)
    depart = models.ForeignKey("Department", on_delete=models.CASCADE, default=1)
class Department(models.Model):
    """
    部门表
    """
    name=models.CharField(max_length=32)
    count=models.IntegerField()
    def __str__(self):
        return self.name

class Customer(models.Model):
    enroll_status_choices = (('signed', "已报名"),
                             ('unregistered', "未报名"),
                             ('studying', '学习中'),
                             ('paid_in_full', "学费已交齐"))
    """
    客户表
    """
    qq = models.CharField('QQ', max_length=64, unique=True, help_text='QQ号必须唯一')
    qq_name = models.CharField('QQ昵称', max_length=64, blank=True, null=True)
    name = models.CharField('姓名', max_length=32, blank=True, null=True, help_text='学员报名后，请改为真实姓名')
    sex_type = (('male', '男'), ('female', '女'))
    sex = models.CharField("性别", choices=sex_type, max_length=16, default='male', blank=True, null=True)
    birthday = models.DateField('出生日期', default=None, help_text="格式yyyy-mm-dd", blank=True, null=True)
    phone = models.BigIntegerField('手机号', blank=True, null=True)
    source = models.CharField('客户来源', max_length=64, choices=source_type, default='qq')
    introduce_from = models.ForeignKey('Customer', verbose_name="转介绍自学员", blank=True, null=True,on_delete=models.CASCADE)
    course = MultiSelectField("咨询课程", choices=course_choices)
    class_type = models.CharField("班级类型", max_length=64, choices=class_type_choices, default='fulltime')
    customer_note = models.TextField("客户备注", blank=True, null=True, )
    status = models.CharField(verbose_name='状态', choices=enroll_status_choices, max_length=64, default="unregistered",
                              help_text="选择客户此时的状态")
    date = models.DateTimeField("咨询日期", auto_now_add=True)
    last_consult_date = models.DateField("最后跟进日期", auto_now_add=True)
    next_date = models.DateField("预计再次跟进时间", blank=True, null=True)
    consultant = models.ForeignKey('UserInfo', verbose_name="销售", related_name='customers', blank=True, null=True,on_delete=models.CASCADE )
    # null= True 是限制数据库里的   blank = True 是限制 ModelForm 的
    class_list = models.ManyToManyField('ClassList', verbose_name="已报班级",blank=True )
    baoming_date = models.DateField("报名时间", null = True,blank=True)

    def __str__(self):
        return self.name+str(self.baoming_date)

    # 以后有 一个东西如果对应多个值就可以这么做非常nice
    def get_classlist(self):
        l=[]
        #正向查询按字段
        for i in self.class_list.all():
            l.append( "<p>'%s'</p>" %(i))
        #     转化成字符串
        return mark_safe(''.join(l))

    # def get_classlist(self):
    #     l=[]
    #     for cls in self.class_list.all():
    #         l.append(str(cls))
    #     return mark_safe(",".join(l))

    #给每个状态设置不同的颜色
    def get_status(self):
        status_color={
            "studying": "green",
            "signed": "#B03060",
            "unregistered": "red",
            "paid_in_full": "blue"
        }
        return mark_safe('<span style="background-color:%s;color:white">%s</span>'%(status_color[self.status],self.get_status_display()))
class Campuses(models.Model):
    """
    校区表
    """
    name = models.CharField(verbose_name='校区', max_length=64)
    address = models.CharField(verbose_name='详细地址', max_length=512, blank=True, null=True)

    def __str__(self):
        return self.name




class ClassList(models.Model):
    """
    班级表
    """
    course = models.CharField("课程名称", max_length=64, choices=course_choices)
    semester = models.IntegerField("学期")
    campuses = models.ForeignKey('Campuses', verbose_name="校区",on_delete=models.CASCADE)
    price = models.IntegerField("学费", default=10000)
    memo = models.CharField('说明', blank=True, null=True, max_length=100)
    start_date = models.DateField("开班日期")
    graduate_date = models.DateField("结业日期", blank=True, null=True)
    #contract = models.ForeignKey('ContractTemplate', verbose_name="选择合同模版", blank=True, null=True,on_delete=models.CASCADE)
    teachers = models.ManyToManyField('UserInfo', verbose_name="老师")
    class_type = models.CharField(choices=class_type_choices, max_length=64, verbose_name='班额及类型', blank=True,
                                  null=True)

    class Meta:
        unique_together = ("course", "semester", 'campuses')

    def __str__(self):
        return "{}{}({})".format(self.get_course_display(), self.semester, self.campuses)
class ConsultRecord(models.Model):
    """
    跟进记录表
    """
    customer = models.ForeignKey('Customer', verbose_name="所咨询客户",on_delete=models.CASCADE)
    note = models.TextField(verbose_name="跟进内容...")
    status = models.CharField("跟进状态", max_length=8, choices=seek_status_choices, help_text="选择客户此时的状态")
    # limit_choices_to 与数据库的没有关系, MOdelForm渲染的时候才有用
    consultant = models.ForeignKey("UserInfo", verbose_name="跟进人", related_name='records',on_delete=models.CASCADE,)
    date = models.DateTimeField("跟进日期", auto_now_add=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)
    def __str__(self):
        return str(self.customer)+str(self.consultant)


class Enrollment(models.Model):
    """
    报名表
    """
    customer = models.ForeignKey('Customer', verbose_name='客户名称',on_delete=models.CASCADE)
    why_us = models.TextField("为什么报名", max_length=1024, default=None, blank=True, null=True)
    your_expectation = models.TextField("学完想达到的具体期望", max_length=1024, blank=True, null=True)
    enrolled_date = models.DateTimeField(auto_now_add=True, verbose_name="报名日期")
    memo = models.TextField('备注', blank=True, null=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)
    school = models.ForeignKey('Campuses',on_delete=models.CASCADE)
    enrolment_class = models.ForeignKey("ClassList", verbose_name="所报班级",on_delete=models.CASCADE)


    class Meta:
        unique_together = ('enrolment_class', 'customer')


class PaymentRecord(models.Model):
    """
    缴费记录表
    """
    customer = models.ForeignKey('Customer', verbose_name="客户",on_delete=models.CASCADE)
    pay_type = models.CharField("费用类型", choices=pay_type_choices, max_length=64, default="deposit")
    paid_fee = models.IntegerField("费用数额", default=0)
    note = models.TextField("备注", blank=True, null=True)
    date = models.DateTimeField("交款日期", auto_now_add=True)
    course = models.CharField("课程名", choices=course_choices, max_length=64, blank=True, null=True, default='N/A')
    class_type = models.CharField("班级类型", choices=class_type_choices, max_length=64, blank=True, null=True,
                                  default='N/A')
    enrolment_class = models.ForeignKey('ClassList', verbose_name='所报班级', blank=True, null=True,on_delete=models.CASCADE)
    consultant = models.ForeignKey('UserInfo', verbose_name="销售",on_delete=models.CASCADE)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)

    status_choices = (
        (1, '未审核'),
        (2, '已审核'),
    )
    status = models.IntegerField(verbose_name='审核', default=1, choices=status_choices)

    confirm_date = models.DateTimeField(verbose_name="确认日期", null=True, blank=True)
    confirm_user = models.ForeignKey(verbose_name="确认人", to='UserInfo', related_name='confirms', null=True,
                                     blank=True,on_delete=models.CASCADE)

class Student(models.Model):
    """
    学生表（已报名）
    """
    customer = models.OneToOneField(verbose_name='客户信息', to='Customer',on_delete=models.CASCADE,null=True,blank=True)
    class_list = models.ManyToManyField(verbose_name="已报班级", to='ClassList', blank=True)

Crm/app01/forms/classstudyrecorder.py
from django import forms
from app01.models import ClassStudyRecord
class ClassStudyRecordForm(forms.ModelForm):
    class Meta:
        model = ClassStudyRecord
        fields="__all__"
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in self.fields.values():
            from multiselectfield.forms.fields import MultiSelectFormField
            from django.forms.fields import BooleanField
            if isinstance(field,BooleanField):
                continue
            if not isinstance(field, MultiSelectFormField):
                field.widget.attrs.update({'class': 'form-control'})

Crm/app01/forms/customers.py
from django import forms
from app01.models import Customer
class CustomerModelForm(forms.ModelForm):
    class Meta:
        model=Customer
        fields="__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            from multiselectfield.forms.fields import MultiSelectFormField
            if not isinstance(field,MultiSelectFormField):
                field.widget.attrs.update({'class':'form-control'})

Crm/app01/forms/eroll.py
from django import forms
from app01.models import Enrollment
class ErollmentForm(forms.ModelForm):
    class Meta:
        model=Enrollment
        exclude=['delete_status']
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in  self.fields.values():
            from multiselectfield.forms.fields import MultiSelectFormField
            if not isinstance(field, MultiSelectFormField):
                field.widget.attrs.update({'class': 'form-control'})

Crm/app01/forms/recoder.py
from django import forms
from app01.models import ConsultRecord
class RecoderCustomerFrom(forms.ModelForm):
    class Meta:
        model = ConsultRecord
        fields = '__all__'

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in self.fields.values():
            from multiselectfield.forms.fields import MultiSelectFormField
            if not isinstance(field,MultiSelectFormField):
                field.widget.attrs.update({'class':'form-control'})

Crm/app01/templates/customers/addcustomer.html
{% extends 'base.html' %}
{% block content %}
    <div class="content-wrapper">
         {% load my %}
         {% bread request %}
          <!-- Content Header (Page header) -->
          <section class="content-header">
              <h1>添加客户
                  <small>Optional description</small>
              </h1>
              <ol class="breadcrumb">
                  <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
                  <li class="active">Here</li>
              </ol>
          </section>

          <!-- Main content -->
          <section class="content">

            <div class="row">
                  <div class="col-md-8 col-md-offset-2">
                      <form action="" method="post">
                        {% csrf_token %}
                         {% for field in form %}
                             <label for="">{{ field.label }}</label>
                             {{ field }} <span>{{ form.errors.0 }}</span>
                         {% endfor %}
                            <button type="submit" class="btn btn-default">提交</button>
                      </form>
                  </div>
            </div>

          </section>
          <!-- /.content -->
      </div>
{% endblock %}

Crm/app01/templates/customers/addrecoderr.html
{% extends 'base.html' %}
{% block content %}
    <div class="content-wrapper">
        {% load my %}
         {% bread request %}
          <!-- Content Header (Page header) -->
          <section class="content-header">
              <h1>添加跟进记录
                  <small>Optional description</small>
              </h1>
              <ol class="breadcrumb">
                  <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
                  <li class="active">Here</li>
              </ol>
          </section>

          <!-- Main content -->
          <section class="content">

            <div class="row">
                  <div class="col-md-8 col-md-offset-2">
                      <form action="" method="post">
                      {% csrf_token %}
                         {% for field in form %}
                             <label for="">{{ field.label }}</label>
                             {{ field }} <span>{{ form.errors.0 }}</span>
                         {% endfor %}
                            <button class="btn btn-default">提交</button>
                      </form>
                  </div>
            </div>

          </section>
          <!-- /.content -->
      </div>
{% endblock %}

Crm/app01/templates/customers/customer_all.html
{% extends 'base.html' %}
{% block content %}


       <div class="content-wrapper">
        {% load my %}
         {% bread request %}

        <!-- Content Header (Page header) -->
        <section class="content-header">

            <h3 class="change">
                {{ lable }}
            </h3>
            <div class="purplesign">
                 <a href="javascript:void(0)" style="background-color: purple;color: white;margin-right: 20px ; ">销售 </a>
                 <a href="?consultant=" style="margin-right: 5px" >全部</a>
                {% for consultant in consultant_list %}
                    {% load filier %}
                    <a href="?{% filter ret consultant.pk  request %}" style="margin-right: 5px" >{{ consultant.username }}</a>
                 {% endfor %}<br><br>
            </div>
            <div class = "redsign">
                <a href="javascript:void(0)" style="background-color: red;color: white;margin-right: 20px  ">状态 </a>
                <a href="?status=" style="margin-right: 5px" >全部</a>
                {% for status in status_list %}
                    <a href="?status={{ status.0}}" style="margin-right: 5px" >{{ status.1 }}</a>

                {% endfor %}<br><br>
            </div>
            <div class = "greensign">
                <a href="javascript:void(0)" style="background-color:green;color: white;margin-right: 20px  ">校区 </a>
                <a href="?class_list__campuses=" style="margin-right: 5px" >全部</a>
                {% for school in campus %}
                    <a href="?class_list__campuses={{ school.pk }}" style="margin-right: 5px" >{{ school.name }}</a>

            {% endfor %}<br><br>

            </div>
            <!--模糊查询的form 表单      完成-->
            <form action=""  method="get" class="pull-right" style="margin-top:30px ">
                 <ol class="breadcrumb">
                     <li>

{#                         select里必须随便写个name给作为键去组成#}
                       <select name="field" id="s1" class="form-control" style="display: inline-block;width: 110px">
                            <option value="">----------------</option>
                            <option value="name">姓名</option>
                            <option value="sex">性别</option>
                            <option value="qq">QQ</option>
                            <option value="phone">手机号</option>
                            <option value="source">客户来源</option>
                            <option value="date">查询日期</option>
                            <option value="status">状态</option>
                            <option value="consultant">销售</option>
                            <option value="class_list">已报班级</option>
                      </select>

                <input style="height: 32px;width: 100px" placeholder="请输入关键字" type="text" name="q">
                <input id="searchbtn" type= 'submit' style="height: 32px;width: 60px;vertical-align: 0px" class="btn btn-success " value="搜索">
                 </li>
                </ol>
            </form>
        </section>

        <!-- Main content -->
           <form action="" method="post" style="margin-top: 10px">
           {% csrf_token %}
              <ol class="breadcrumb">
                     <select name="action" id="" class="form-control" style="display: inline-block;width: 240px">
                         <option value="">请选择批量处理方法</option>
                         <option value="patch_delete">删除</option>
                         {% if lable == '我的客户' %}
                            <option class= "change1" value="patch_change_public">私户转公户</option>
                         {% else %}
                            <option class= "change1" value="patch_change">公户转私户</option>
                         {% endif %}

                     </select>
                    <button style="vertical-align: 0px" class="btn btn-danger">提交</button>
            </ol>
            <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                        <div class="box-header">
                            {% if "customersaddall"|showorhide:request %}
                                    <a style="font-size: 14px" href="{% url "addcustomers" %}{{ next }}"
                                       class="box-title btn btn-success btn-sm">添加客户</a>

                                {% endif %}
                        <a style="font-size: 14px" class="box-title btn btn-warning btn-sm"
                                       id="allbtn">全选</a>
                        </div>

                        <!-- /.box-header -->
                        <div class="box-body">
                            <table  id="example2" class="text-center table table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th>选择</th>
                                        <th>编号</th>
                                        <th>客户姓名</th>
                                        <th>性别</th>
                                        <th>QQ</th>
                                        <th>手机号</th>
                                        <th>客户来源</th>
                                        <th>咨询日期</th>
                                        <th>当前状态</th>
                                        <th>销售</th>
                                        <th>所报班级</th>
                                        <th>跟进记录</th>

                                        {% if "customerseditall"|showorhide:request or "customersdelall"|showorhide:request %}
                                            <th>操作</th>
                                        {% endif %}

                                    </tr>
                                </thead>
                                <tbody>
                                {% for customers in customers_list %}
                                <tr>
                                    <td><input type="checkbox" name="select_id" value="{{ customers.pk }}"></td>
                                    <td>{{ forloop.counter|add:pagination.num}}</td>
                                    <td>{{ customers.name }}</td>
{#                                  如果不加就显示元组sex_type = (('male', '男'), ('female', '女'))前面的值加了之后就显示后面的字段                                          #}
                                    <td>{{ customers.get_sex_display }}</td>
                                    <td>{{ customers.qq }}</td>
                                    <td>{{ customers.phone }}</td>
                                    <td>{{ customers.get_source_display }}</td>
                                    <td>{{ customers.date|date:"Y-m-d" }}</td>
                                    <td>{{ customers.get_status }}</td>
                                    <td>{{ customers.consultant|default:'暂无' }}</td>
{#                                    以前是这样的#}
{#                                    <td>{% for customers in customers.class_list.all %}#}
{#                                        <span>{{ customers }}</span>#}
{#                                        {% if  not forloop.last %}#}
{#                                            ,#}
{#                                        {% endif %}#}
{#                                    {% endfor %}#}
{#                                    </td>#}
{#                                新学了一种#}
                                    <td>{{ customers.get_classlist|default:'暂无' }}</td>
                                    <td><a href="/customer/recoder/?pk={{ customers.pk }}">跟进记录</a></td>

                                        {% if "customerseditall"|showorhide:request or "customersdelall"|showorhide:request %}
                                            <td>
                                                {% if "customerseditall"|showorhide:request %}
                                                    <a href="{% url "editcustomers" customers.pk %}{{ next }} "
                                                       class="btn btn-success btn-sm"> <i class="fa fa-edit  fa-lg"></i>
                                                    </a>
                                                {% endif %}
                                                &nbsp;
                                                {% if "customersdelall"|showorhide:request %}
                                                    <a href="{% url "delcustomers" customers.pk %}{{ next }}"
                                                       class="btn btn-success btn-sm"><i
                                                            class="fa fa-trash-o fa-lg"></i> </a></td>


                                                {% endif %}




                                        {% endif %}

                                </tr>
                                {% endfor %}



                                </tbody>
                            </table>
                            <nav aria-label="Page navigation" class="pull-right">
                                  <ul class="pagination">
                                        {{ pagination.page_html|safe }}
                                  </ul>
                            </nav>
                        </div>
                        <!-- /.box-body -->
                    </div>
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
           </form>

        <!-- /.content -->
    </div>

{% endblock %}
{% block js %}
{#    如果搜索字段是状态和性别,完美#}
    <script>
        {#$(".purplesign a").click(function () {#}
        {# $(this).parent().nextattr('href',"?{{ ret.consultant }}" + "&{{ ret.status }}")#}
        {#})#}

        $('#s1').change(function () {
            $(this).next().replaceWith("<input style='height: 32px;width: 100px'  type='text' name='q'>")
           if($(this).val()==='sex'){
              s1={'female':'女','male':'男'}
           $(this).next().replaceWith('<select name="q" id="s2" class="form-control" style="display: inline-block;width: 100px" </select>')
           $.each(s1,function(i,j){
                $("#s2").append("<option value="+i+ ">"+j+"</option>")
                                 })
           }
           if($(this).val()==='status'){
            {#enroll_status_choices = (('signed', "已报名"),#}
            {#             ('unregistered', "未报名"),#}
            {#             ('studying', '学习中'),#}
            {#             ('paid_in_full', "学费已交齐"),)#}
               enroll_status_choices={"signed":'已报名',"unregistered":'未报名',"studying":"学习中","paid_in_full":'学费已交齐'}
             $(this).next().replaceWith('<select name="q" id="s2" class="form-control" style="display: inline-block;width: 100px" </select>')
           $.each(enroll_status_choices,function(i,j){
                $("#s2").append("<option value="+i+ ">"+j+"</option>")
                                 })
           }

        })
        $("#allbtn").click(function () {
            if ( $('input[type=checkbox]').is(':checked')){
                $('input[type=checkbox]').attr("checked",false)
            }else{
                $('input[type=checkbox]').attr("checked",true)
            }
        })


    </script>
{% endblock %}